export enum LocalizationMessage {
  CUSTOMER_CREATE_SUCCESSFULLY = 'CUSTOMER_CREATE_SUCCESSFULLY',
  CUSTOMER_ALREADY_EXISTS = 'CUSTOMER_ALREADY_EXISTS',
  CUSTOMER_EMAIL_ALREADY_EXISTS = 'CUSTOMER_EMAIL_ALREADY_EXISTS',
  CUSTOMER_UPDATE_SUCCESSFULLY = 'CUSTOMER_UPDATE_SUCCESSFULLY',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_GET_SUCCESSFULLY = 'CUSTOMER_GET_SUCCESSFULLY',
  GET_PAGINATION_SUCCESSFULLY = 'GET_PAGINATION_SUCCESSFULLY',
  VALIDATE_OBJECT_ID = 'VALIDATE_OBJECT_ID',
  NO_UPDATE_DATA_PROVIDED = 'NO_UPDATE_DATA_PROVIDED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
} 