export enum LocalizationMessage {
  CUSTOMER_CREATE_SUCCESSFULLY = 'customer.CUSTOMER_CREATE_SUCCESSFULLY',
  CUSTOMER_UPDATE_SUCCESSFULLY = 'customer.CUSTOMER_UPDATE_SUCCESSFULLY',
  CUSTOMER_NOT_FOUND = 'customer.CUSTOMER_NOT_FOUND',
  CUSTOMER_EMAIL_ALREADY_EXISTS = 'customer.CUSTOMER_EMAIL_ALREADY_EXISTS',
  CUSTOMER_ALREADY_EXISTS = 'customer.CUSTOMER_ALREADY_EXISTS',
  NO_UPDATE_DATA_PROVIDED = 'customer.NO_UPDATE_DATA_PROVIDED',
  INTERNAL_SERVER_ERROR = 'common.INTERNAL_SERVER_ERROR',
  VALIDATE_OBJECT_ID = 'common.VALIDATE_OBJECT_ID',
  CUSTOMER_GET_SUCCESSFULLY = 'customer.CUSTOMER_GET_SUCCESSFULLY',
  GET_PAGINATION_SUCCESSFULLY = 'customer.GET_PAGINATION_SUCCESSFULLY',
}
