export enum LocalizationMessage {
  INTERNAL_SERVER_ERROR = 'common.INTERNAL_SERVER_ERROR',
  CUSTOMER_CREATE_SUCCESSFULLY = 'customer.CUSTOMER_CREATE_SUCCESSFULLY',
  CUSTOMER_ALREADY_EXISTS = 'customer.CUSTOMER_ALREADY_EXISTS',
  CUSTOMER_EMAIL_ALREADY_EXISTS = 'customer.CUSTOMER_EMAIL_ALREADY_EXISTS',
}
