# docker-compose.yml
version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: customer-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: crud-nestjs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

volumes:
  mongo_data:
