version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: nestjs-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nestjs_db
    networks:
      - nestjs-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/nestjs_db
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  mongodb_data: 